export const Films = [
    {
        id : 1,
        img:"assets/images/Film1.jpg",
        title:"Spirited Away", 
        year:"20/7/2001",
        Score_IMDb:"10/10", 
        author:"Miyazaki Hayao",
        Type:"Animation , Adventure  , Fantasty",
        Country:"Japan",
        duration:"75 minutes",
        manufacturer:"Studio Ghibli",
        info:"10-year-old Chihiro (Daveigh Chase) moves with her parents to a new home in the Japanese countryside. After taking a wrong turn down a wooded path, Chihiro and her parents discover an amusement park with a stall containing an assortment of food. To her surprise, Chihiro's parents begin eating and then transform into pigs. In this supernatural realm, Chihiro encounters a host of characters and endures labor in a bathhouse for spirits, awaiting a reunion with her parents.",
        trailer:`https://www.youtube.com/embed/ByXuk9QqQkk`,
    },
    {
        id : 2,
        img:"assets/images/Film2.jpg",
        title:"Howl's moving castle", 
        year:"20/11/2004",
        Score_IMDb:"9.7/10", 
        author:"Miyazaki Hayao",
        Type:"Animation , Adventure, Anime  , Fantasty",
        Country:"Japan",
        duration:"119 minutes",
        manufacturer:"Walt Disney Pictures, Studio Ghibli",
        info:"Sophie (Emily Mortimer) has an uneventful life at her late father's hat shop, but all that changes when she befriends wizard Howl (Christian Bale), who lives in a magical flying castle. However, the evil Witch of Waste (Lauren Bacall) takes issue with their budding relationship and casts a spell on young Sophie, which ages her prematurely. Now Howl must use all his magical talents to battle the jealous hag and return Sophie to her former youth and beauty",
        trailer:`https://www.youtube.com/embed/iwROgK94zcM`,
    },
    {
        id : 3  ,
        img:"assets/images/Film3.jpg",
        title:"Tonari no Totoro", 
        year:"16/4/1988",
        Score_IMDb:"9/10", 
        author:"Miyazaki Hayao",
        Type:" , Adventure, Anime  , Fantasty",
        Country:"Japan",
        duration:"86 minutes",
        manufacturer:"Walt Disney Pictures, Studio Ghibli",
        info:"When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.",
        trailer:`https://www.youtube.com/embed/92a7Hj0ijLs`
    },
    {
        id : 4  ,
        img:"assets/images/Film4.jpg",
        title:"One Piece", 
        year:"16/4/2001",
        Score_IMDb:"9.5/10", 
        author:"Eiichiro Oda ",
        Type:" Action, Adventure, Anime  , Fantasty",
        Country:"Japan",
        duration:"112 minutes",
        manufacturer:"Toei Animation",
        info:"The Straw Hat Pirates leave for the island of Elegia to attend a concert by Uta, a world-famous singer. After Uta performs her first song New Genesis, Luffy goes on stage to reunite with her, revealing that the two of them know each other because Uta is the adopted daughter of Red-Haired Shanks. They met when Shanks was based at Luffy's hometown 12 years ago, but one day he returned from a voyage without her, claiming she had left to pursue a career as a singer.",
        trailer:`https://www.youtube.com/embed/2pD50-A3OKk`,    
    },
    {
        id : 5  ,
        img:"assets/images/Film5.jpg",
        title:"Suzume no Tojiamri ", 
        year:"8/4/2023",
        Score_IMDb:"9.5/10", 
        author:"Shinaki Makoto",
        Type:" Romance,Action, Adventure,  Fantasty",
        Country:"Japan",
        duration:"190 minutes",
        manufacturer:"CoMix Wave Films",
        info:"The film follows 17-year-old high school student Suzume Iwato and Souta Munakata, who team up to prevent a series of disasters across Japan. Sometime later, back in Kyushu, Suzume is on her way to school when she once again runs into Souta, walking up the same road where they first met.",
        trailer:`https://www.youtube.com/embed/F7nQ0VUAOXg`
    },
    {
        id : 6  ,
        img:"assets/images/Film6.jpg",
        title:"Summer Wars ", 
        year:"1/5/2009",
        Score_IMDb:"9.9/10", 
        author:"Mamoru Hosoda",
        Type:" Romance,Action, Adventure, Games",
        Country:"Japan",
        duration:"120 minutes",
        manufacturer:"Mad House",
        info:"The film tells the story of Kenji Koiso, a timid eleventh-grade math genius who is taken to Ueda by twelfth-grade student, Natsuki Shinohara to celebrate her great-grandmother's 90th birthday. However, he is falsely implicated in the hacking of a virtual world by a self-aware, sadistic artificial intelligence named Love Machine. Kenji must repair the damage done, and find a way to stop the rogue computer program from causing any further chaos.",
        trailer:`https://www.youtube.com/embed/UbmdYasVDDg`,
    },
    {
        id : 7  ,
        img:"assets/images/Film7.jpg",
        title:"Your Name", 
        year:"27/7/2017",
        Score_IMDb:"10/10", 
        author:"ShinKai Makoto",
        Type:" Romance,, Adventure, Anime,Best Movie Films",
        Country:"Japan",
        duration:"120 minutes",
        manufacturer:"CoMix Wave Films",
        info:"In depicts the story of high school students Taki Tachibana and Mitsuha Miyamizu, who suddenly begin to swap bodies despite having never met, unleashing chaos on each other's lives. It features the voices of Ryunosuke Kamiki and Mone Kamishiraishi, with animation direction by Masashi Ando, character design by Masayoshi Tanaka, and its orchestral score and soundtrack composed by Radwimps. A light novel of the same name, also written by Shinkai, was published a month prior to the film premiere. It was inspired by Japans frequency for natural disasters.",
        trailer:`https://www.youtube.com/embed/_mifHzxFNQ4`,
     },
    {
        id : 8  ,
        img:"assets/images/Film8.jpg",
        title:"The Girl Time", 
        year:"23/2/2009",
        Score_IMDb:"9.2/10", 
        author:"Takashi Watanabei ",
        Type:" Romance,, Adventure, Anime,Best Movie Films",
        Country:"Japan",
        duration:"98 minutes",
        manufacturer:"Madhouse",
        info:"At Kuranose High School in Tokyo, Japan, 17-year-old Makoto Konno discovers a message written on a blackboard and ends up inadvertently falling onto a walnut-shaped object. On her way to the Tokyo National Museum to meet with her aunt, Kazuko Yoshiyama, she is ejected into a railroad crossing when the brakes on her bicycle fail and hit by an oncoming train, but finds herself transported back in time when she was riding her bicycle right before the accident",
        trailer:`https://www.youtube.com/embed/eWnTeKEsDlU`,
    },
    {
        id : 9  ,
        img:"assets/images/Film9.jpg",
        title:"The Wind Rises", 
        year:"12/2/2006",
        Score_IMDb:"8.5/10", 
        author:"	Toshio Suzuki",
        Type:" Romance,, Adventure, Anime,Best Movie Films",
        Country:"Japan",
        duration:"119 minutes",
        manufacturer:"	Studio Ghibli",
        info:"The Wind Rises was the highest-grossing Japanese film in Japan in 2013. It received critical acclaim, with praise for its animation, music, and emotional weight, though some opinions were mixed regarding the film's subject matter. It was nominated for several awards, including the Academy Award for Best Animated Feature, the Golden Globe Award for Best Foreign Language Film, and the Japan Academy Prize for Animation of the Year, winning the latter.",
        trailer:`https://www.youtube.com/embed/PhHoCnRg1Yw`,
    },
    

    {
        id : 10  ,
        img:"assets/images/Film10.jpg",
        title:"Demon Slayer-Train", 
        year:"12/8/2020",
        Score_IMDb:"9.5/10", 
        author:"Haruo Sotozaki",
        Type:"Action,  Adventure, Anime,Best Movie Films",
        Country:"Japan",
        duration:"200 minutes",
        manufacturer:"Funimation - Dolby Digital",
        info:"Falling forever into an endless dream... Tanjiro and the group have completed their rehabilitation training at the Butterfly Mansion, and they arrive to their next mission on the Mugen Train, where over 40 people have disappeared in a very short period of time. Tanjiro and Nezuko, along with Zenitsu and Inosuke, join one of the most powerful swordsmen within the Demon Slayer Corps, Flame Hashira Kyojuro Rengoku, to face the demon aboard the Mugen Train on track to despair.",
        trailer:`https://www.youtube.com/embed/ATJYac_dORw`,
    },
    


    {
        id : 11  ,
        img:"assets/images/Film11.jpg",
        title:"DragonBall Super: Broly", 
        year:"12/8/2018",
        Score_IMDb:"9.5/10", 
        author:"Akira Toriyama",
        Type:"Action,  Adventure, Anime,Best Movie Films",
        Country:"Japan",
        duration:"200 minutes",
        manufacturer:"Toei Aniomation , Fuji Television, Bandai ,  Dolby Digital",
        info:"Goku and Vegeta encounter Broly, a Saiyan warrior . A advanture of Songoku and Vegeta to kill BNroly and at the last time to action they are win , sure it is win , The most effective advanture abttle",
        trailer:`https://www.youtube.com/embed/wuIbeQv3v7c`,    
    },



    {
        id : 12  ,
        img:"assets/images/Film12.jpg",
        title:"Koe no Katachi", 
        year:"1/8/2017",
        Score_IMDb:"9.9/10", 
        author:"Yamada Naoko",
        Type:"School , Romance, Violence, Anime,Best Movie Films",
        Country:"Japan",
        duration:"130 minutes",
        manufacturer:"Kyōto Animation",
        info:"The main content of the film revolves around the two main characters, Ishida Shōya and the innocent born friend Nishimiya Shōko - their relationship has drawn the connection between people and also the frustrations in communication. . [4] The work is based on the manga of the same name written and illustrated by female manga author Ōima Yoshitoki; The original manga has been licensed to Tieu Publishing House under the official Vietnamese title, Shape of Sound",
        trailer:`https://www.youtube.com/embed/nfK6UgLra7g`,
    },
    ];
    
    